openapi: 3.0.0
info:
  description: 'API DOCUMENTATION'
  version: 1.0.0
  title: Poloniex API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: ' https://poloniex.com'
tags:
  - name: Public
    description: Please note that making more than 6 calls per second to the public API, or repeatedly and needlessly fetching excessive amounts of data, can result in your IP being banned.
  - name: Trading
    description: For programmatic trading of crypto currencies
paths:
  /public?command=returnTicker:
    get:
      tags:
        - Public
      summary: Market Meta Data
      operationId: getMarkets
      description: |
        Used to get the open and available trading markets at Bittrex along with other meta data.
      responses:
        '200':
components:
  schemas:
  parameters: